services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: micromanager
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql  # Ajoutez cette ligne pour persister les données

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"

# Déclarez le volume nommé ici
volumes:
  mariadb_data: